version: '3'

services:
  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - "3306:3306"

  redis:
    image: redis:4.0
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"

  rabbitmq:
    image: rabbitmq:3.7.6-management
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    ports:
      - "5672:5672"

        #  vault:
        #    image: vault:1.0.1
        #    ports:
        #      - "8200:8200"
        #    environment:
        #      SKIP_SETCAP: 1
        #      VAULT_TOKEN: changeme
        #      VAULT_DEV_ROOT_TOKEN_ID: changeme
        #      VAULT_ADDR: http://vault:8200

volumes:
  db_data:
  rabbitmq_data:
  redis_data:
