default: &default
  adapter: mysql2
  encoding: utf8
  collation: utf8_general_ci
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV.fetch('DATABASE_HOST') { '127.0.0.1' } %>
  port: 3306
  username: <%= ENV.fetch('DATABASE_USER') { 'root' } %>
  password: <%= ENV['DATABASE_PASS'] %>

development:
  <<: *default
  database: baselogic_development

test:
  <<: *default
  database: baselogic_test

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 64 } %>
  database: <%= ENV.fetch('DATABASE_NAME') { 'baselogic_production' } %>
